# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Bump Maven version

on:
  release:
    types: [created]

jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: sonatype-oss

      - name: Fetch Latest Release
        id: latest_release
        uses: thebritican/fetch-latest-release@v1.0.2
        with:
          github_token: ${{ github.token }}

      - name: Bump Maven version
        shell: bash
        run: |
          bash .scripts/set_version.sh ${{ steps.latest_release.outputs.tag_name }}
          git config --global user.name 'Auto PR'
          git config --global user.email 'autopr@emarshall.dev'
          git commit -am "Bump package version to ${{ steps.latest_release.outputs.tag_name }}"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.AUTO_PR_TOKEN }}
